### ISSUE TITLE
Holy Crap! And what's this all about?

### ISSUE THREAD

**Issue by andredublin** [Buzztrax/buzzmachines#4]
First off I have to say holy :poop:! I haven't used buzzmachines since 98'.  Its really awesome to see it alive on github.

Now, are you guys taking over the work from Jeskola?
Is there any way I can contribute to this/these projects?

**Comment by ensonic** [comment]
Hi & Welcome! The buzzmachines we have in the repo have beein released as open source by the authors - we've spend quite some time to search for them and kindly asked to release the sources. You can imagine that it gets harder every year.

We'd love to get you working on the project. First lets get the build on macosx working:
http://wiki.buzztrax.org/index.php/Building#MacOSX

We're using (irc)[irc://freenode.net/#buzztrax] and (gitter chat)[https://gitter.im/Buzztrax/buzztrax] - please join. I am based in europe, lets see if we can manage to be there at the same time :)

**Comment by andredublin** [comment]
I'm based in South Carolina, I'll be on gitter and irc.
