### ISSUE TITLE
Machine porting request: FSM KickXP

### ISSUE THREAD

**Issue by Gimmeapill** [Buzztrax/buzzmachines#5]
Hello,

I hope this is the right place to post machine porting requests.
I miss the FSM KickXP (http://www.buzzmachines.com/machineinfo.php?id=741) which has one significant feature over the regular FSM kick generator: it can be tuned and play notes to match the root note of the pattern.
Looking at  the sourceforge buzzmachines archive, the source for that one seems to be missing, so I was just wondering if it was forgotten or if FSM didn't wish to provide it?

BR,

LX

**Comment by trusktr** [comment]
It's likely that the source isn't anywhere to be found, or closed source, otherwise I bet @ensonic would've included it.

**Comment by ensonic** [comment]
I've found them. The folder is a bit of a mess, I'll carefully check which version is the one that got released.

**Comment by Gimmeapill** [comment]
Cool, thx ;-)

**Comment by Gimmeapill** [comment]
Seems to work fine - thanks, that was fast!
